In [3]:

import numpy as np
print(np.random.randint(888))

247


In [ ]:
import pandas as pd

# Données pour chaque onglet
base_data = {
    "Commande": ["import pandas as pd", "pd.Series()", "pd.DataFrame()", "df.head()", "df.info()"],
    "Description": ["Importer la bibliothèque", "Créer une série", "Créer un DataFrame", "Afficher les premières lignes", "Résumé des données"],
    "Exemple": ["import pandas as pd", "pd.Series([1,2,3])", "pd.DataFrame({'a': [1,2]})", "df.head(5)", "df.info()"]
}

selection_filtrage_data = {
    "Commande": ["df['col']", "df.loc[]", "df.iloc[]", "df[df['age'] > 30]"],
    "Description": ["Accéder à une colonne", "Sélection par étiquette", "Sélection par index", "Filtrer les lignes"],
    "Exemple": ["df['age']", "df.loc[0, 'age']", "df.iloc[0, 1]", "df[df['age'] > 30]"]
}

manipulation_data = {
    "Commande": ["df['new'] = ...", "df.drop()", "df.rename()", "df.sort_values()"],
    "Description": ["Ajouter une colonne", "Supprimer colonnes/lignes", "Renommer colonnes", "Trier les données"],
    "Exemple": ["df['double'] = df['age'] * 2", "df.drop('col', axis=1)", "df.rename(columns={'a': 'A'})", "df.sort_values(by='age')"]
}

analyse_agregation_data = {
    "Commande": ["df.describe()", "df.mean()", "df.groupby()", "df.pivot_table()"],
    "Description": ["Statistiques descriptives", "Moyenne", "Regroupement", "Tableau croisé dynamique"],
    "Exemple": ["df.describe()", "df['age'].mean()", "df.groupby('genre').mean()", "df.pivot_table(values='age', index='genre')"]
}

lecture_ecriture_data = {
    "Commande": ["pd.read_csv()", "df.to_csv()", "pd.read_excel()", "df.to_excel()"],
    "Description": ["Lire un fichier CSV", "Écrire un CSV", "Lire un Excel", "Exporter en Excel"],
    "Exemple": ["pd.read_csv('data.csv')", "df.to_csv('export.csv')", "pd.read_excel('fichier.xlsx')", "df.to_excel('export.xlsx')"]
}


base_df = pd.DataFrame(base_data)
selection_df = pd.DataFrame(selection_filtrage_data)
manipulation_df = pd.DataFrame(manipulation_data)
analyse_df = pd.DataFrame(analyse_agregation_data)
lecture_df = pd.DataFrame(lecture_ecriture_data)


with pd.ExcelWriter("Fiche_Revision_Pandas.xlsx") as writer:
    base_df.to_excel(writer, sheet_name="Base", index=False)
    selection_df.to_excel(writer, sheet_name="Selection_Filtrage", index=False)
    manipulation_df.to_excel(writer, sheet_name="Manipulation", index=False)
    analyse_df.to_excel(writer, sheet_name="Analyse_Agregation", index=False)
    lecture_df.to_excel(writer, sheet_name="Lecture_Ecriture", index=False)



In [ ]:
import numpy as np
n=np.random.random((3,2))
n=np.random.randint(1,5,(2,3))
s=np.random.randint(1,60,25)
print(n)
print(n)
print(s)
print("nouvaux matrice")
print(np.reshape(s,(5,5)))
t=np.arange(36).reshape((6,6))
print(t)


In [33]:
import pandas as pd 
import numpy as np
data_book={"book1":"2/12/2002","book2":"8/12/2009","book3":"2/12/2009","book4":"9/12/2007","book5":"2/12/2020"}
author_book={"book1":"oumar","book2":"sidi","book3":"ahmed","book4":"ali","book5":"melike"}
print(data_book)
print(author_book)
final_data={"data":data_book,"Author":author_book}
# print(pd.Series(final_data))
# print(pd.DataFrame(final_data))
# print(pd.DataFrame(final_data).index)
# print(pd.DataFrame(final_data,columns=['Author'],index=["book1","book2"]))
n=[{i:i*10} for i in range(1,10)]
# print(n)
number=[g for h in n for g in h]
value=[ g for h in n for g in h.values()]
print(number)
print(value)

# print([g for h in n for g in h])
print(pd.DataFrame({"n":number,"v":value}))
print(pd.DataFrame(np.random.rand(9,2)))
# print(pd.DataFrame(data_book))
# test=[[2,8],[2,10],[3,11],[3,14]]
# print(pd.DataFrame(test,columns=["X","Y"]))
# print(np.random.rand(9,2))
print(pd.DataFrame([{"nom":"ali","prenom":"sidi"}]))
print(pd.DataFrame({"nom":["ali"],"prenom":["sidi"]}))

{'book1': '2/12/2002', 'book2': '8/12/2009', 'book3': '2/12/2009', 'book4': '9/12/2007', 'book5': '2/12/2020'}
{'book1': 'oumar', 'book2': 'sidi', 'book3': 'ahmed', 'book4': 'ali', 'book5': 'melike'}
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
   n   v
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  60
6  7  70
7  8  80
8  9  90
          0         1
0  0.583184  0.334685
1  0.548794  0.263977
2  0.196109  0.380038
3  0.725125  0.058351
4  0.083274  0.911478
5  0.487832  0.634552
6  0.612188  0.657240
7  0.895252  0.396126
8  0.508240  0.881208
   nom prenom
0  ali   sidi
   nom prenom
0  ali   sidi


In [ ]:
import pandas as pd 
import numpy as np

data={
    "NAME":["SIDI","AHMED","NORMAL"],
    "Age":[20,19,15],
    "City":["araffat","Londom","tavra9e wyne"]
}
# df=pd.DataFrame(data,index=pd.RangeIndex(5,8))
df=pd.DataFrame(data)
print(df) 
df=pd.DataFrame(data)
n=df.rename(index={0:"A",1:"B",2:"C"})
print(n)
print(n.iloc[1])
nember=np.arange(4)
print(nember)
name=["bana","hh","ll","oo","ttt"]
print(pd.Series(name) )
# df.set_index('NAME',inplace=True)
# print(df)
# print(np.random.randint(1,36,(6,6)))
# print(np.arange(36).reshape((6,6)))

     NAME  Age          City
0    SIDI   20       araffat
1   AHMED   19        Londom
2  NORMAL   15  tavra9e wyne
     NAME  Age          City
A    SIDI   20       araffat
B   AHMED   19        Londom
C  NORMAL   15  tavra9e wyne
NAME     AHMED
Age         19
City    Londom
Name: B, dtype: object
[0 1 2 3]
0    bana
1      hh
2      ll
3      oo
4     ttt
dtype: object
[[35 27 27  2 26 31]
 [23 25 28  1  7 14]
 [ 8 34  9 13  3  3]
 [20 33 19  8 21 35]
 [ 7 11 30 32 14  1]
 [27  1 29  4 15 20]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [38]:
import pandas as pd
import numpy as np
df=pd.read_csv("Orders.csv",skiprows=4)
# df.info()
# df.describe()
df
df.loc[df["Status"]==True,"hh"]='donne'
df.loc[df["Status"]==False,"hh"]='pending'
df.loc[(df["Status"]==False)&(df["Order Date"]<="2023-01-01"),"hh" ]='concted'
# df.dropna(how="all")
# df[df["Country"]=="Saudi Arabic"]
df[(df["Category"]=="Laptop") | (df["Category"]=="Smartphone")]
# df.loc[df["Status"]==True,"hh"]
df[df["Item"].str.contains('S21',na=False)]
df[df["Sub Category"].str.startswith('Apple',na=False)]
df["Phone Number"]=df["Phone Number"].str.replace("Tel:","")
# df
df["Discount"]=df["Discount"].round(0)
df["total des"]=df["Quantity"]*df["Unit Price"]
df["Cost"]=df["total des"]-df["Discount"].fillna(0)
df.insert(9,'custum full name',df["Customer First Name"]+" "+df['Customer Last Name'])
df["Branch"].str[:2]
def level(row):
    if row>1000:
        return "Height"
    else:
        return "low"
df["COST level"]=df["Cost"].apply(level)
df

Order ID Order Date               Country        City Branch      Lat  \
0           1.0   1/1/2023                 Syria        homs   hs01  34.7326   
1           2.0   1/1/2023          Saudi Arabia      riyadh   rd01  24.7136   
2           3.0   1/1/2023          Saudi Arabia      riyadh   rd03  24.7743   
3           NaN        NaN                   NaN         NaN    NaN      NaN   
4           4.0   1/1/2023  United Arab Emirates   abu dhabi   ad01  24.4539   
...         ...        ...                   ...         ...    ...      ...   
19999   19996.0   1/9/2023               Morocco  casablanca   cs01  33.5731   
20000   19997.0   1/9/2023                 Syria        homs   hs01  34.7326   
20001   19998.0   1/9/2023                   USA   las vegas   lv01  36.1699   
20002   19999.0   1/9/2023          Saudi Arabia      jeddah   jd03  21.4858   
20003   20000.0   1/9/2023                   USA  washington   wh01  38.9072   

            Lng Customer First Name Customer Last Name custum full name  ...  \
0       36.7136                lina          alrrashid   lina alrrashid  ...   
1       46.6753                omar              eurul       omar eurul  ...   
2       46.7386                iman           iismaeil    iman iismaeil  ...   
3           NaN                 NaN                NaN              NaN  ...   
4       54.3773               ahmad              rihan      ahmad rihan  ...   
...         ...                 ...                ...              ...  ...   
19999    7.5898               ahmad                iad        ahmad iad  ...   
20000   36.7136                 ali              kiali        ali kiali  ...   
20001 -115.1398              husayn             salayk    husayn salayk  ...   
20002   39.1925               fatin            bahriin    fatin bahriin  ...   
20003  -77.0369               ahmad             shakur     ahmad shakur  ...   

                        Item SalesPerson ID Quantity Unit Price Discount  \
0        iPad   Pro   12.9"            N498      1.0      999.0     40.0   
1       Galaxy  S21  Ultra             X918      1.0     1199.0    120.0   
2       Panasonic Lumix GH5            I036      1.0     1299.0      NaN   
3                        NaN            NaN      NaN        NaN      NaN   
4             Galaxy Tab A8            E804      2.0      199.0     28.0   
...                      ...            ...      ...        ...      ...   
19999      PlayStation 4 Pro           M210      1.0      399.0     12.0   
20000           Fossil Gen 6           Z826      2.0      299.0     60.0   
20001          PlayStation 2           K624      1.0       99.0      3.0   
20002         JBL Live 500BT           Y368      1.0       99.0      4.0   
20003  Galaxy Watch Active 2           Y590      1.0      249.0      5.0   

      Status       hh  total des    Cost COST level  
0      False  concted      999.0   959.0        low  
1       True    donne     1199.0  1079.0     Height  
2       True    donne     1299.0  1299.0     Height  
3        NaN      NaN        NaN     NaN        low  
4       True    donne      398.0   370.0        low  
...      ...      ...        ...     ...        ...  
19999   True    donne      399.0   387.0        low  
20000   True    donne      598.0   538.0        low  
20001   True    donne       99.0    96.0        low  
20002   True    donne       99.0    95.0        low  
20003   True    donne      249.0   244.0        low  

[20004 rows x 24 columns]